const START_QUOTE_LOADING = 'START_QUOTE_LOADING'
const END_QUOTE_LOADING = 'END_QUOTE_LOADING'
const SET_QUOTES = 'SET_QUOTES'

export {
    START_QUOTE_LOADING,
    END_QUOTE_LOADING,
    SET_QUOTES
}